name: ActionsWorkflow

on:
  # Scheduled to run automatically at 0:00 Saturday UTC.
  schedule:
    - cron: "0 0 * * SAT"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automated-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipx
        run: pip3 install --user pipx

      - name: Ensure pipx is in path
        run: pipx ensurepath

      - name: Install cfpages-prune
        run: pipx install git+https://github.com/karldreher/cfpages-prune.git

      - name: Delete preview deployments in Cloudflare account
        run: cfpages-prune --redact
        env:
          CF_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          CF_AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
          CF_API_KEY: ${{ secrets.API_KEY }}
