name: ActionsWorkflow

on:
  # Scheduled to run automatically at 0:00 Saturday UTC.  
  schedule:
    - cron:  '0 0 * * SAT'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Delete preview deployments in Cloudflare account
        run: python3 deletePreviewDeployments.py
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
