name: ActionsWorkflow

on:
  # Scheduled to run automatically at 0:00 Saturday UTC.  
  schedule:
    - cron:  '0 0 * * SAT'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pipx
        run: pip3 install --user pipx

      - name: Ensure pipx is in path
        run: pipx ensurepath

      - name: Install cf_pages_delete_previews
        run: pipx install git+https://github.com/karldreher/cloudflare-pages-delete-revisions.git@develop

      - name: Delete preview deployments in Cloudflare account
        run: cf_pages_delete_previews --redact
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
