name: test-and-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Poetry Install
        run: poetry install --with dev,release

      - name: Pytest
        run: poetry run pytest
        env:
          CF_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          CF_AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
          CF_API_KEY: ${{ secrets.API_KEY }}

      - name: Semantic Release Preview
        run: |
          poetry run semantic-release print-version

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Poetry Install
        run: poetry install --with dev,release

      - name: Semantic Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release publish
        env:
          GH_TOKEN: {{ secrets.GH_TOKEN }}
