name: Test

on:
  pull_request:

jobs:
  test:
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.3
        virtualenvs-create: true
        virtualenvs-in-project: false

    - name: Set up cache
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: poetry install
      if: steps.poetry-cache.outputs.cache-hit != 'true'

    - name: Pytest
      run: poetry run pytest
